---
name: bin-wxcat
version: v0.0.1
author:
  - 'Eric Wilhelm @ <ewilhelm at cpan dot org>'
abstract: pipe output to an unfocussed window
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=bin-wxcat
  homepage: http://scratchcomputing.com/
  license: http://dev.perl.org/licenses/
  repository: http://scratchcomputing.com/svn/bin-wxcat/trunk
requires:
  Class::Accessor::Classy: v0.9.0
  Getopt::Helpful: 0.04
  Wx: 0.27
  wxPerl::Constructors: v0.0.4
  wxPerl::Styles: v0.0.1
build_requires:
  Module::Build: 0.26
  Test::More: 0
provides:
  bin::wxcat:
    file: lib/bin/wxcat.pm
    version: v0.0.1
generated_by: Module::Build version 0.280802
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
